### ISSUE TITLE
Retrieving delimiters from syntax nodes like `LuaCallArgList`

### ISSUE THREAD

**Issue by elenakrittik** [CppCXY/emmylua-analyzer-rust#1]
Hello! I'm asking this not as a user of `emmylua-analyzer`, but as a fellow dev working on a language toolkit. I'm currently implementing a CST based on `rowan`, and am struggling to find any example of how to get delimiters out of things like call expression arguments. Going through the reverse-dependents on `rowan`, i've found this repository, which seems fairly active and uses a recent `rowan` version.

Looking at the `syntax` module you have, and at `LuaCallArgList` specifically, there doesn't seem to be any way to retrieve delimiters between function arguments. Did you think of how to solve this yet? Or maybe i overlooked a solution?

Thank you in advance, and i hope i don't disturb your project's development too much with unrelated questions.

UPD: Just 10 minutes after opening this, i found out about `SyntaxNode.children_with_tokens()`, which seems exactly like what i need. I'll leave this open if you have anything to add, but if not feel free to close right away. Sorry!

**Comment by CppCXY** [comment]
You can find many uses of rowan in my parser. My parser is based on the one from rust-analyzer, except all the code is handwritten.
